### ISSUE TITLE
Integrated TTS

### ISSUE THREAD

**Issue by amcdnl** [svrooij/node-sonos-ts#161]
Awesome package, thanks for building this.

It would be awesome if the TTS was integrated natively. There are a variety of solutions out there that might make this possible like: https://www.npmjs.com/package/say

Wanted to see if you had explored this before ... if nothing else it would make it easier for others to get started.

**Comment by amcdnl** [comment]
@svrooij - Yup - I saw that package. My only fear about a remote TTS would be time. I'm using this to notify me when motion is outside my home and the faster the better. My google nest cams -> homebridge -> homekit -> sonos.

**Comment by svrooij** [comment]
What this package does in essence is:

1. Hash the text an language
2. Check if local file exists (cached :wink:) 
3. Query the remote TTS service to generate audio for some text
4. Save the generated audio as an mp3 on the local system (with the hash as filename)
5. Run the [notification](https://svrooij.io/node-sonos-ts/sonos-device/notifications-and-tts.html#notifications) command

If speed is the main concern, you could of course pre-generate the mp3 files and host them on a webserver locally. And instead of calling the tts command, you would call the notification command with your local hosted files.

You could even consider sponsoring me, and use my cloud hosted version to pre-generate your mp3 files that you then save locally.

**Comment by svrooij** [comment]
How about build support for [home assistant text to speech](https://www.home-assistant.io/integrations/tts/#post-apitts_get_url) since everybody is already using that anyway.

**Comment by amcdnl** [comment]
Thanks for the link!

I actually use Homebridge ( though I'm probably going to end up moving to HomeAssistant for more advanced things ) and I actually wrote a quick plugin using your library - https://github.com/amcdnl/homebridge-sonos-announcer to do what I wanted.

While we are on the topic, I was trying to resolve a file locally but I got mime type errors. I was wondering if you had a good example of how you would do that.

```
manager.PlayNotification({
  trackUri: path.resolve('./hello.mp3')
});
```

Reference: https://github.com/amcdnl/homebridge-sonos-announcer/blob/master/src/index.ts#L72

**Comment by svrooij** [comment]
Your Sonos speaker cannot access files from the machine running the script. You have to run a small webserver that will serve the mp3.

Like if you would host an html file.
This is exactly what I meant by all the things you need to include, this is also the reason for me to build a  separate library just for tts

**Comment by amcdnl** [comment]
> Your Sonos speaker cannot access files from the machine running the script. You have to run a small webserver that will serve the mp3.

Ah, I see how it works now. Ok all that makes sense. Thanks for explaining that.
