### ISSUE TITLE
No reponse in docker container

### ISSUE THREAD

**Issue by cph0x00** [svrooij/node-sonos-ts#184]
A few days ago I moved my iobroker instance from physical host into a docker container with a new IP (NAT). I can start the Sonos instance in the moved iobroker instance and it turns green. 
iobroker log reports: _starting. Version 3.0.0 in /opt/iobroker/node_modules/iobroker.sonos, node: v18.19.0, js-controller: 5.0.17_

But that's all. I cannot perform any actions and neither are any values updated. 
I guess this is because of the network address translation in the container. It might work if I could provide a callback IP address. 
Any suggestions how I could make the Sonos adapter work in my container?

**Comment by svrooij** [comment]
I don't do `iobroker` and your description is pretty cryptic.

I guess you're having trouble with the event not arriving? Have you checked the docs on the topic?
https://sonos-ts.svrooij.io/sonos-device/events.html

Since you're running in docker you have to expose the `6329` port from the host to the container. And you have to set the `SONOS_LISTENER_HOST` environment variable to the IP off your docker host.
