### ISSUE TITLE
Question: Difference between ServiceEvent, DeviceEvent

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#75]
I started to develop a SONOS event node for Node-RED, based on your library. Subscribing to and receiving events works fine. 

Question: What is the difference between SonosEvents, ServiceEvents? 

My understanding is that ONLY the LastChange event is submitted - all others are moderated. 

> Therefore, the Rendering Control Service event model defines a specialized state variable (LastChange) that is used exclusively for eventing individual state changes. In this model, the LastChange state change is the only variable that is evented using the standard UPnP event mechanism. All other state variables are indirectly evented via the LastChange state variable. (Note:
A_ARG_TYPE_ state variables are not evented, either directly or indirectly.)

**Comment by svrooij** [comment]
Each service emits events https://github.com/svrooij/node-sonos-ts/blob/master/src/services/base-service.ts#L429 They are available at device.ServiceName.Events

The Sonos device subscribes to AvControl and RenderingControl https://github.com/svrooij/node-sonos-ts/blob/master/src/sonos-device.ts#L521 and makes the Sonos device emit the following events. https://github.com/svrooij/node-sonos-ts/blob/master/src/models/sonos-events.ts#L47

Does this answer your question?

**Comment by hklages** [comment]
Yes. But I am not sure whether I understand it. 

Why does the Sonos device only subscribes to AvControl and RenderingControl - there are about 10 services? Just because you picked up the most important? 

What happens If I subscribe to volume and mute? Does that results in one or multiple subscription to RenderingControl? What happens if I unsubscribe first to volume and later to mute? After un-subscribing to both the subscription to RenderingControl is un-subscribed?

**Comment by svrooij** [comment]
Not all services provide useful events. The ZoneGroup service doesn’t need to be subscribed to from multiple speakers. The audio in service is only available on speakers that have an audio in port.

I picked the most important services and aggregate the events. Volume events are also used by the notification part for instance. If you subscribe to events on the Sonos device, a subscription for the RenderingControl service and the AvControl service are started. If you also subscribe to those services the events are routed to both handlers but it won’t create an extra subscription on the actual speaker.

Because the events are routed the a speaker/service specific endpoint [see here](https://github.com/svrooij/node-sonos-ts/blob/c1f56796f1489774beb2fbd4ca862619d8e4510a/src/sonos-event-listener.ts#L96).
It is only possible for each service from each device to have a single subscription. If by accident a service wants to create a new subscription, it will simply be connected to the existing subscription.

**Comment by hklages** [comment]
Thanks - no it is clear to me.
