### ISSUE TITLE
AVTransportService events - outputs also unchanged properties

### ISSUE THREAD

**Issue by hklages** [svrooij/node-sonos-ts#77]
Using this code (node.send is just to output the data):

`playerKueche.AVTransportService.Events.on(ServiceEvents.Data, data => {
      node.send({ payload: data, topic: 'AVTransportService' })
    })`

Result: When pushing "stop" at Sonos app all properties and not only the changed one (here TransportState) are provided. 

When using the RenderingService only the changed properties are output - as expected.

**Comment by svrooij** [comment]
The code to parse the events it [here](https://github.com/svrooij/node-sonos-ts/blob/master/src/services/base-service.ts#L420-L491). There isn't any difference between parsing the events, there also isn't any caching the previous value (at service level).

I've just tested the local [events example](https://github.com/svrooij/node-sonos-ts/blob/master/examples/events.js) and it seems like sonos doesn't respect the UPNP specs.
They are pushing all events when something changes on AVTransport and only the changed value in RenderingControl.

Since we don't cache it in the library (yet), we cannot do change detection. Is this something we need to do?

**Comment by hklages** [comment]
> Since we don't cache it in the library (yet), we cannot do change detection. Is this something we need to do?

No. Node-RED provides an RBE node (Report by Exception node - only passes on data if the payload has changed). That could do the job - I hope. 

Thanks for the fast response!
