### ISSUE TITLE
Parse ChannelMapSet from zone group state

### ISSUE THREAD

**Issue by gauthierm** [svrooij/node-sonos-ts#97]
The API makes it looks like this might return an object but because it's returned as embedded XML, it gets returned as a string.

I can decode and parse the XML manually, but it would be nice if it was done by default.

Additionally, the returned data looks to be global and not related to the current device. Should the API go on the SonosManager rather than the SonosDevice?

**Comment by svrooij** [comment]
Have you checked `GetParsedZoneGroupState` which is not generated like the rest, but is a manual created method that gets added to the Zone group topology service.

https://github.com/svrooij/node-sonos-ts/blob/6fedb44644c68f6796920f729c25dae751f8e33c/src/services/zone-group-topology.service.ts#L165-L180

**Comment by svrooij** [comment]
@gauthierm You were totally right about the difficulty of extending those services. I've changed things so that the extensions don't live in the templates anymore.

And in the above commit (which also mentions you) I've added your changes. Can you check that it still works on your setup? And maybe add the **ChannelMapSet** to the static [ZoneGroupState response](https://github.com/svrooij/node-sonos-ts/blob/feature/parse-stereo-pairs/tests/services/responses/zone-group.GroupState.xml) that is used for testing. Once you add a ChannelMapSet in the xml, it will automatically be tested, (since this response is used for all tests that use the ZoneGroupState).

**Comment by hklages** [comment]
I use beta-4.

ZoneGroupTopologyService  event now delivers property ChannelMapSet either as undefined or in case of paired speakers as object. 

In Sonos documentation it always declared as string.

**Comment by svrooij** [comment]
@hklages do you think that is an issue? Do you have a screenshot so we can have a look at it?

**Comment by hklages** [comment]
I created a stereopair from "Bad" (192.168.178.35) and A E.r_k-er:1(192.168.178.38) and the coordinator in that group is "Küche" (192.168.178.37). As you can see on the picture, Küche has as channelMap undefined, the stereopair players have objects and both have the same name "Bad". What you can not see (missing property hidden) is that A E.r_k-er:1 is hidden. Compared to the SONOS app there is a difference as the SONOS app does not show hidden player in a group. 

In your documentation at [Sonos Docs](https://svrooij.io/node-sonos-ts/sonos-device/services/device-properties-service.html#addbondedzones)

It is just inconsistent to documentation. I can live with it.  

![channelMapSet](https://user-images.githubusercontent.com/17273119/104562204-57774380-5648-11eb-9b62-447c6dd40129.png)

**Comment by hklages** [comment]
It would be helpful to have the "hidden" attribute - in the output of the list. Is it available in the xml for notify?

**Comment by svrooij** [comment]
> Is it available in the xml from notify?

I guess not, because the event properties are generated from the device description.

**Comment by hklages** [comment]
> It would be helpful to have the "hidden" attribute - in the output of the list. Is it available in the xml from notify?

>> I guess not, because the event properties are generated from the device description.

sorry - my fault. 

The name is not hidden but "**Invisible**" and this attribute is buried in the event xml data from ZoneGroupState string. 
Alle invisible players are not shown in the Sonos app. You "create" an invisible player for instance when binding together a stereo pair.  
It is important to know whether a player is "Invisible" because in that case many commands do not work. 

Is there the chance to to get the raw notify data for all events? Then I can extract what i need.
